# Netherite removal settings
anti-netherite:
  # CHECKS

  # Should we clear netherite in the inventory of players?
  clear: false
  # Should we cancel crafting of netherite items?
  cancel-craft: true
  # Should we cancel equipping of netherite items?
  cancel-equip: true
  # Should we cancel attacking with netherite items?
  cancel-attack: true

  # TIMINGS
  
  # Delay in seconds between each check (assuming you leave multiplier at 20)
  delay: 1
  # Multiply the delay by this number to get the actual delay
  # 20 = 20 ticks = 1 second
  multiplier: 20