name: AntiNetherite
description: Disables Netherite and Netherite crafts
version: '${project.version}'
main: top.modpotato.Main
api-version: '1.20'
folia-supported: true

commands:
  antinetherite:
    description: Manage AntiNetherite plugin settings
    usage: /antinetherite [reload|get|set] [setting] [value]
    permission: antinetherite.manage
    aliases: [an]

permissions:
  antinetherite.manage:
    description: Allows managing AntiNetherite plugin settings
    default: op