name: ${name}
description: ${description}
version: '${version}'
main: top.modpotato.Main
api-version: '1.20'
folia-supported: true
authors: [${author}]

commands:
  antinetherite:
    description: Manage AntiNetherite plugin settings
    usage: |
      /<command> reload - Reload the configuration
      /<command> restore-debris [world] - Restore all replaced Ancient Debris (optionally in a specific world)
      /<command> debris-info - Show information about stored Ancient Debris locations
      /<command> get <setting> - Get a configuration value
      /<command> set <setting> <value> - Set a configuration value
    permission: antinetherite.manage
    aliases: [an]

permissions:
  antinetherite.manage:
    description: Allows managing AntiNetherite plugin settings
    default: op