name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Update version based on commit count
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        VERSION="$(echo $COMMIT_COUNT)"
        echo "New version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
        sed -i "s/version=INDEV/version=$VERSION/" gradle.properties
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: antinetherite-${{ env.VERSION }}
        path: build/libs